#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8082
  test-mail: jira4jr@gmail.com
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

# Основные настройки Spring //TODO thymeleaf
spring:
  profiles:
    active: prod #//TODO change
  messages:
    basename: jira-mail
    encoding: UTF-8

  thymeleaf:
    cache: false
    encoding: UTF-8
    check-template-location: false

  init:
    mode: never
  jpa:
    show-sql: true
    format-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/jira


    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikar-url:
  liquibase:
    changeLog: "classpath:db/changelog.sql"
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 3d0d8738e65881fff266
            client-secret: 0f97031ce6178b7dfb67a6af587f37e222a16120
            scope:
              - email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          gitlab:
            client-id: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
            client-secret: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email
  sql:
    init:
      mode: always
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587

# Настройки логирования
logging:

  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    com.javarush.jira.common.config.ThymeleafConfig: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.thymeleaf: INFO

# Настройки сервера
server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: ${SR_PORT}

# Настройки Swagger
springdoc.swagger-ui.path: /doc
